### ISSUE TITLE
GuiObject can't decide which way it should be rotated

### ISSUE THREAD

**Issue by Vikmanou** [jaipack17/Nature2D#1]
I'm using Nature2D along with a drag module to be able to drag the GuiObject across the screen. When dragging, I noticed that the ImageLabel kept rotating upwards and downwards and couldn't decide even if my mouse was kept still while holding.

I attached the place file where this issue occurs below in a mega. It also appears that smaller sizes of GuiObjects are not effected by this bug.
https://mega.nz/file/ORcTXI6T#N3Jh9cpRK976d2nQsBfzw4O4jnoJaaBx7WX6-rGujU4

**Comment by jaipack17** [comment]
@string-dot-byte This should be fixed now! If you encounter the bug again, you can open another issue for the same!
