### ISSUE TITLE
self is nil in Engine:Start() method

### ISSUE THREAD

**Issue by Lemon6K** [jaipack17/Nature2D#39]
"Engine:83: attempt to index nil with 'canvas' " is the error.
This happens when i call the method Start() in Engine class.

Also if I try to call to call method CreateCanvas in Engine class it will drops
"Engine:354: canvas is not a valid member of Players.Player.PlayerGui.Main.Canvas" - meaning that the **self** is the frame in this case.

**Comment by jaipack17** [comment]
Do you still encounter this issue? If so, could you share a demo place-file where I can take a look at it?
