### ISSUE TITLE
Getting the error "RenderStepped event can only be used from local scripts" when using engine:Start()

### ISSUE THREAD

**Issue by mincraft0990** [jaipack17/Nature2D#42]
Excuse me if I make any silly mistakes or misunderstand something since I am fairly new to this engine, but I am trying to follow the "Creating RigidBodies" guide on the documentation, and I get the error "RenderStepped event can only be used from local scripts" when I use engine:Start()

![Screen Shot 2022-12-24 at 11 05 37 AM](https://user-images.githubusercontent.com/82071274/209443529-57f0657e-fdea-4814-bbbc-87ec82987d8b.png)

**Comment by Dsioul** [comment]
it's because RenderStepped event is a client side event... since the rendering of the UI is local on roblox. 
just switch your script to a local script.
