### ISSUE TITLE
GuiObject flying out of the screen

### ISSUE THREAD

**Issue by string-dot-byte** [jaipack17/Nature2D#8]
I have been encountering an issue for a while which is where the gui just goes through the ScreenGui and never to be seen again.

It usually occurs when its too far into the screen’s edges. It’s also ocurring with a spring when set the 2nd point too far.

I probably suck at explaining, I have a video demonstrating here.

https://user-images.githubusercontent.com/68619882/142344890-771a3408-4068-4c6f-8dc6-b3c748e31d7a.mp4

**Comment by jaipack17** [comment]
Should be fixed now, you can close this if you no longer encounter the issue! Thanks!

**Comment by string-dot-byte** [comment]
Thanks! All good now! <3
